import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/antd/AntdRegistry";
import AuthListener from "./AuthListener";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <StyledComponentsRegistry>
                <body className={`!min-h-screen ${inter.className}`}>
                    <AuthListener />
                    {children}
                </body>
            </StyledComponentsRegistry>
        </html>
    );
}
